export const DiTypes = {
	Application: Symbol.for('Application'),
	ILogger: Symbol.for('ILogger'),
	MulterConfig: Symbol.for('MulterConfig'),
	AuthController: Symbol.for('AuthController'),
	UserController: Symbol.for('UserController'),
	UploadsController: Symbol.for('UploadsController'),
	UserService: Symbol.for('UserService'),
	ConfigService: Symbol.for('ConfigService'),
	PrismaService: Symbol.for('PrismaService'),
	TokenService: Symbol.for('TokenService'),
	MailService: Symbol.for('MailService'),
	CookieService: Symbol.for('CookieService'),
	UsersRepository: Symbol.for('UsersRepository'),
	TokensRepository: Symbol.for('TokensRepository'),
	ExeptionFilter: Symbol.for('ExeptionFilter'),
};
